# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
unordered_multichain_mode: true # When true, strict cross chain ordering of event processing will not be obeyed.
rollback_on_reorg: false
contracts:
  - name: PoolManager
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 indexed id, uint256 amount)
      - event: Donate(bytes32 indexed id, address indexed sender, uint256 amount0, uint256 amount1, int24 tick)
      - event: DynamicLPFeeUpdated(bytes32 indexed id, uint24 dynamicLPFee)
      - event: Initialize(bytes32 indexed id, address indexed currency0, address indexed currency1, address hooks, uint24 fee, bytes32 parameters, uint160 sqrtPriceX96, int24 tick)
      - event: ModifyLiquidity(bytes32 indexed id, address indexed sender, int24 tickLower, int24 tickUpper, int256 liquidityDelta, bytes32 salt)
        field_selection: # Additional fields available to index to augment data
          transaction_fields:
            - "hash"
            - "from"
      - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
      - event: Paused(address account)
      - event: ProtocolFeeControllerUpdated(address indexed protocolFeeController)
      - event: ProtocolFeeUpdated(bytes32 indexed id, uint24 protocolFee)
      - event: Swap(bytes32 indexed id, address indexed sender, int128 amount0, int128 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick, uint24 fee, uint16 protocolFee)
        field_selection: # Additional fields available to index to augment data
          transaction_fields:
            - "hash"
            - "from"
      - event: Transfer(address caller, address indexed from, address indexed to, uint256 indexed id, uint256 amount)
      - event: Unpaused(address account)
  - name: PositionManager
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 indexed id)
      - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
      - event: Subscription(uint256 indexed tokenId, address indexed subscriber)
      - event: Transfer(address indexed from, address indexed to, uint256 indexed id)
      - event: Unsubscription(uint256 indexed tokenId, address indexed subscriber)
networks:
  - id: 56
    start_block: 50000000
    contracts:
      - name: PositionManager
        address:
          - 0x55f4c8aba71a1e923edc303eb4feff14608cc226
      - name: PoolManager
        address:
          - 0xa0ffb9c1ce1fe56963b0321b32e7a0302114058b
